// Icon system — uses local SVG files from public/icons/
// Manifest is auto-generated by scripts/build-icon-manifest.cjs
// Run `node scripts/build-icon-manifest.cjs` after adding new SVG files

export interface IconDef {
  id: string
  name: string
  category: string
  // Public URL path to the SVG, e.g. "/icons/aws/Compute/ec2.svg"
  url: string
}

// Inline the types needed by the manifest to avoid circular deps
export type IconCategory = string

// Import from auto-generated manifest (manifest imports IconDef type from this file)
// We use a direct import to avoid re-export issues
import { ICON_CATEGORIES as _ICON_CATEGORIES, ICON_MANIFEST } from './icon-manifest'

export const ICON_CATEGORIES = _ICON_CATEGORIES

// The full icon list
export const ICONS: IconDef[] = [...ICON_MANIFEST]

export function searchIcons(query: string): IconDef[] {
  const q = query.toLowerCase().trim()
  if (!q) return ICONS
  return ICONS.filter(icon => {
    const name = icon.name.toLowerCase()
    const cat = icon.category.toLowerCase()
    const id = icon.id.toLowerCase()
    const url = icon.url.toLowerCase()
    // Prioritize name matches
    if (name.includes(q)) return true
    if (id.includes(q)) return true
    if (cat.includes(q)) return true
    if (url.includes(q)) return true
    // Fuzzy: match individual words
    const words = q.split(/\s+/)
    return words.every(w => name.includes(w) || id.includes(w) || cat.includes(w))
  }).sort((a, b) => {
    // Sort: name starts with query first, then name contains, then others
    const aName = a.name.toLowerCase()
    const bName = b.name.toLowerCase()
    const aStarts = aName.startsWith(q) ? 0 : aName.includes(q) ? 1 : 2
    const bStarts = bName.startsWith(q) ? 0 : bName.includes(q) ? 1 : 2
    if (aStarts !== bStarts) return aStarts - bStarts
    return aName.localeCompare(bName)
  })
}

export function getIconsByCategory(category: string): IconDef[] {
  if (category === 'all') return ICONS
  return ICONS.filter(icon => icon.category === category)
}
