import { useDiagramStore } from '../../stores/diagramStore'
import { X, Download, AlertTriangle, AlertCircle, CheckCircle, Clock, Zap, TrendingUp, Shield } from 'lucide-react'
import type { SimulationReport } from '../../types'

function formatNumber(n: number): string {
  if (n >= 1000000) return (n / 1000000).toFixed(1) + 'M'
  if (n >= 1000) return (n / 1000).toFixed(1) + 'K'
  return n.toLocaleString()
}

function SeverityBadge({ severity }: { severity: number }) {
  const color = severity >= 80 ? 'bg-error/20 text-error' : severity >= 60 ? 'bg-warning/20 text-warning' : 'bg-info/20 text-info'
  return (
    <span className={`px-1.5 py-0.5 rounded text-[9px] font-medium ${color}`}>
      {severity}%
    </span>
  )
}

function downloadReport(report: SimulationReport, scenarioName?: string) {
  const now = new Date()
  const date = now.toISOString().split('T')[0]
  const time = now.toTimeString().split(' ')[0].slice(0, 5)

  let md = `# System Design Simulation Report\n`
  md += `**Date:** ${date}\n`
  md += `**Time:** ${time}\n`
  if (scenarioName) md += `**Scenario:** ${scenarioName}\n`
  md += `**Simulation Duration:** ${report.duration} ticks\n\n`

  md += `---\n\n`
  md += `## Executive Summary\n`
  md += `- **Final Availability:** ${report.summary.finalAvailability}%\n`
  md += `- **P95 Latency:** ${report.summary.p99Latency}ms\n`
  md += `- **Total Requests:** ${formatNumber(report.summary.totalRequests)}\n`
  md += `- **Success Rate:** ${report.summary.successRate}%\n`
  md += `- **Error Budget Remaining:** ${report.summary.errorBudgetRemaining}%\n\n`

  md += `---\n\n`
  md += `## Node Performance\n\n`
  md += `| Node | Type | Avg RPS | Avg Latency | Utilization | Peak Error | Status | Events |\n`
  md += `|------|------|---------|-------------|-------------|------------|--------|--------|\n`
  report.nodeSummaries.forEach(ns => {
    md += `| ${ns.nodeName} | ${ns.nodeType} | ${formatNumber(ns.avgRps)} | ${ns.avgLatency}ms | ${(ns.avgUtilization * 100).toFixed(0)}% | ${(ns.peakErrorRate * 100).toFixed(1)}% | ${ns.status} | ${ns.events} |\n`
  })

  if (report.incidents.length > 0) {
    md += `\n---\n\n`
    md += `## Incident History\n\n`
    md += `| Timestamp | Component | Issue | Explanation | Severity | Recommendation |\n`
    md += `|-----------|-----------|-------|-------------|----------|----------------|\n`
    report.incidents.forEach(inc => {
      md += `| ${inc.timestamp} | ${inc.componentName} | ${inc.issue} | ${inc.explanation} | ${inc.severity}% | ${inc.recommendation} |\n`
    })
  }

  if (report.recommendations.length > 0) {
    md += `\n---\n\n`
    md += `## Engineering Recommendations\n`
    report.recommendations.forEach((rec, i) => {
      md += `${i + 1}. **${rec.split(' ').slice(0, 3).join(' ')}:** ${rec}\n`
    })
  }

  md += `\n---\n\n`
  md += `*Generated by SysSim — System Design Simulator*\n`

  const blob = new Blob([md], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `simulation_report_${Date.now()}.md`
  a.click()
  URL.revokeObjectURL(url)
}

export function ReportModal() {
  const showReport = useDiagramStore(s => s.showReport)
  const setShowReport = useDiagramStore(s => s.setShowReport)
  const lastReport = useDiagramStore(s => s.lastReport)

  if (!showReport || !lastReport) return null

  const report = lastReport
  const criticalIncidents = report.incidents.filter(i => i.severity >= 80).length
  const warningIncidents = report.incidents.filter(i => i.severity >= 60 && i.severity < 80).length

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm" onClick={() => setShowReport(false)}>
      <div
        className="bg-surface border border-border rounded-xl shadow-2xl w-[720px] max-h-[85vh] overflow-hidden flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-border shrink-0 bg-gradient-to-r from-accent/5 to-transparent">
          <div>
            <h2 className="text-base font-bold text-text flex items-center gap-2">
              <Zap className="w-4 h-4 text-accent" />
              Simulation Report
            </h2>
            <p className="text-[10px] text-text-dim mt-0.5">
              {new Date(report.generatedAt).toLocaleString()} · {report.duration} ticks
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => downloadReport(report, report.scenarioName)}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-accent text-white rounded-lg text-xs font-medium hover:bg-accent/90 transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              Download .md
            </button>
            <button onClick={() => setShowReport(false)} className="p-1.5 rounded-lg hover:bg-surface-hover text-text-dim hover:text-text transition-colors">
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-5 space-y-5">
          {/* Executive Summary */}
          <div>
            <h3 className="text-xs font-semibold text-text-dim uppercase tracking-widest mb-3 flex items-center gap-1.5">
              <TrendingUp className="w-3.5 h-3.5" />
              Executive Summary
            </h3>
            <div className="grid grid-cols-5 gap-2">
              <SummaryCard label="Availability" value={`${report.summary.finalAvailability}%`} status={report.summary.finalAvailability >= 95 ? 'good' : report.summary.finalAvailability >= 85 ? 'warning' : 'bad'} />
              <SummaryCard label="P99 Latency" value={`${report.summary.p99Latency}ms`} status={report.summary.p99Latency <= 100 ? 'good' : report.summary.p99Latency <= 300 ? 'warning' : 'bad'} />
              <SummaryCard label="Total Requests" value={formatNumber(report.summary.totalRequests)} status="neutral" />
              <SummaryCard label="Success Rate" value={`${report.summary.successRate}%`} status={report.summary.successRate >= 95 ? 'good' : report.summary.successRate >= 85 ? 'warning' : 'bad'} />
              <SummaryCard label="Error Budget" value={`${report.summary.errorBudgetRemaining}%`} status={report.summary.errorBudgetRemaining >= 50 ? 'good' : report.summary.errorBudgetRemaining >= 20 ? 'warning' : 'bad'} />
            </div>
          </div>

          {/* Node Performance */}
          {report.nodeSummaries.length > 0 && (
            <div>
              <h3 className="text-xs font-semibold text-text-dim uppercase tracking-widest mb-3 flex items-center gap-1.5">
                <Shield className="w-3.5 h-3.5" />
                Node Performance
              </h3>
              <div className="border border-border rounded-lg overflow-hidden">
                <table className="w-full text-[10px]">
                  <thead>
                    <tr className="bg-surface-hover/50 text-text-dim">
                      <th className="text-left px-3 py-2 font-medium">Node</th>
                      <th className="text-right px-2 py-2 font-medium">Avg RPS</th>
                      <th className="text-right px-2 py-2 font-medium">Latency</th>
                      <th className="text-right px-2 py-2 font-medium">Util</th>
                      <th className="text-right px-2 py-2 font-medium">Errors</th>
                      <th className="text-center px-2 py-2 font-medium">Status</th>
                      <th className="text-right px-3 py-2 font-medium">Events</th>
                    </tr>
                  </thead>
                  <tbody>
                    {report.nodeSummaries.map(ns => (
                      <tr key={ns.nodeId} className="border-t border-border/50 hover:bg-surface-hover/30">
                        <td className="px-3 py-2">
                          <div className="font-medium text-text">{ns.nodeName}</div>
                          <div className="text-text-dim text-[9px]">{ns.nodeType}</div>
                        </td>
                        <td className="text-right px-2 py-2 text-text font-mono">{formatNumber(ns.avgRps)}</td>
                        <td className="text-right px-2 py-2 text-text font-mono">{ns.avgLatency}ms</td>
                        <td className="text-right px-2 py-2 font-mono">
                          <span className={ns.avgUtilization > 0.8 ? 'text-error' : ns.avgUtilization > 0.6 ? 'text-warning' : 'text-text'}>
                            {(ns.avgUtilization * 100).toFixed(0)}%
                          </span>
                        </td>
                        <td className="text-right px-2 py-2 font-mono">
                          <span className={ns.peakErrorRate > 0.1 ? 'text-error' : ns.peakErrorRate > 0.05 ? 'text-warning' : 'text-text'}>
                            {(ns.peakErrorRate * 100).toFixed(1)}%
                          </span>
                        </td>
                        <td className="text-center px-2 py-2">
                          <span className={`px-1.5 py-0.5 rounded text-[9px] font-medium ${
                            ns.status === 'running' ? 'bg-success/20 text-success' :
                            ns.status === 'degraded' ? 'bg-warning/20 text-warning' :
                            ns.status === 'failed' ? 'bg-error/20 text-error' :
                            'bg-surface-hover text-text-dim'
                          }`}>
                            {ns.status}
                          </span>
                        </td>
                        <td className="text-right px-3 py-2 text-text-dim font-mono">{ns.events}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Incident History */}
          {report.incidents.length > 0 && (
            <div>
              <h3 className="text-xs font-semibold text-text-dim uppercase tracking-widest mb-3 flex items-center gap-1.5">
                <AlertTriangle className="w-3.5 h-3.5" />
                Incident History
                <span className="ml-auto flex items-center gap-2 font-normal normal-case tracking-normal">
                  {criticalIncidents > 0 && <span className="text-error">{criticalIncidents} critical</span>}
                  {warningIncidents > 0 && <span className="text-warning">{warningIncidents} warning</span>}
                  <span className="text-text-dim">{report.incidents.length} total</span>
                </span>
              </h3>
              <div className="border border-border rounded-lg overflow-hidden">
                <table className="w-full text-[10px]">
                  <thead>
                    <tr className="bg-surface-hover/50 text-text-dim">
                      <th className="text-left px-3 py-2 font-medium w-16">Time</th>
                      <th className="text-left px-2 py-2 font-medium">Component</th>
                      <th className="text-left px-2 py-2 font-medium">Issue</th>
                      <th className="text-left px-2 py-2 font-medium">Details</th>
                      <th className="text-center px-2 py-2 font-medium w-16">Sev</th>
                    </tr>
                  </thead>
                  <tbody>
                    {report.incidents.slice(-50).map((inc, i) => (
                      <tr key={i} className={`border-t border-border/50 hover:bg-surface-hover/30 ${inc.severity >= 80 ? 'bg-error/5' : inc.severity >= 60 ? 'bg-warning/5' : ''}`}>
                        <td className="px-3 py-1.5 text-text-dim font-mono">{inc.timestamp}</td>
                        <td className="px-2 py-1.5 font-medium text-text">{inc.componentName}</td>
                        <td className="px-2 py-1.5 text-text">{inc.issue}</td>
                        <td className="px-2 py-1.5 text-text-dim max-w-[200px] truncate" title={inc.explanation}>{inc.explanation}</td>
                        <td className="text-center px-2 py-1.5"><SeverityBadge severity={inc.severity} /></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Recommendations */}
          {report.recommendations.length > 0 && (
            <div>
              <h3 className="text-xs font-semibold text-text-dim uppercase tracking-widest mb-3 flex items-center gap-1.5">
                <CheckCircle className="w-3.5 h-3.5" />
                Engineering Recommendations
              </h3>
              <div className="space-y-1.5">
                {report.recommendations.map((rec, i) => (
                  <div key={i} className="flex items-start gap-2 px-3 py-2 rounded-lg bg-surface-hover/30 border border-border/50">
                    <span className="text-[10px] font-bold text-accent mt-0.5 shrink-0">{i + 1}.</span>
                    <span className="text-[10px] text-text leading-relaxed">{rec}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

function SummaryCard({ label, value, status }: { label: string; value: string; status: 'good' | 'warning' | 'bad' | 'neutral' }) {
  const borderColor = status === 'good' ? 'border-success/30' : status === 'warning' ? 'border-warning/30' : status === 'bad' ? 'border-error/30' : 'border-border'
  const valueColor = status === 'good' ? 'text-success' : status === 'warning' ? 'text-warning' : status === 'bad' ? 'text-error' : 'text-text'

  return (
    <div className={`px-3 py-2.5 rounded-lg border ${borderColor} bg-surface-hover/20`}>
      <div className="text-[9px] text-text-dim uppercase tracking-wider mb-1">{label}</div>
      <div className={`text-sm font-bold ${valueColor}`}>{value}</div>
    </div>
  )
}
